heroku config:set SENDGRID_USER=judasfrancis
heroku config:set SENDGRID_PASSWORD=secret

export STRIPE_API_KEY=sk_test_B5RUJ3ZgW7BnB5VKp1vNbE7e;
export STRIPE_PUBLIC_KEY=pk_test_w5BDNvBFAjPzc5qJJRusg93V;
