require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BatchCharitiesController do

  # This should return the minimal set of attributes required to create a valid
  # BatchCharity. As you add validations to BatchCharity, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "batch_id" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BatchCharitiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all batch_charities as @batch_charities" do
      batch_charity = BatchCharity.create! valid_attributes
      get :index, {}, valid_session
      assigns(:batch_charities).should eq([batch_charity])
    end
  end

  describe "GET show" do
    it "assigns the requested batch_charity as @batch_charity" do
      batch_charity = BatchCharity.create! valid_attributes
      get :show, {:id => batch_charity.to_param}, valid_session
      assigns(:batch_charity).should eq(batch_charity)
    end
  end

  describe "GET new" do
    it "assigns a new batch_charity as @batch_charity" do
      get :new, {}, valid_session
      assigns(:batch_charity).should be_a_new(BatchCharity)
    end
  end

  describe "GET edit" do
    it "assigns the requested batch_charity as @batch_charity" do
      batch_charity = BatchCharity.create! valid_attributes
      get :edit, {:id => batch_charity.to_param}, valid_session
      assigns(:batch_charity).should eq(batch_charity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BatchCharity" do
        expect {
          post :create, {:batch_charity => valid_attributes}, valid_session
        }.to change(BatchCharity, :count).by(1)
      end

      it "assigns a newly created batch_charity as @batch_charity" do
        post :create, {:batch_charity => valid_attributes}, valid_session
        assigns(:batch_charity).should be_a(BatchCharity)
        assigns(:batch_charity).should be_persisted
      end

      it "redirects to the created batch_charity" do
        post :create, {:batch_charity => valid_attributes}, valid_session
        response.should redirect_to(BatchCharity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved batch_charity as @batch_charity" do
        # Trigger the behavior that occurs when invalid params are submitted
        BatchCharity.any_instance.stub(:save).and_return(false)
        post :create, {:batch_charity => { "batch_id" => "invalid value" }}, valid_session
        assigns(:batch_charity).should be_a_new(BatchCharity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BatchCharity.any_instance.stub(:save).and_return(false)
        post :create, {:batch_charity => { "batch_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested batch_charity" do
        batch_charity = BatchCharity.create! valid_attributes
        # Assuming there are no other batch_charities in the database, this
        # specifies that the BatchCharity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BatchCharity.any_instance.should_receive(:update_attributes).with({ "batch_id" => "" })
        put :update, {:id => batch_charity.to_param, :batch_charity => { "batch_id" => "" }}, valid_session
      end

      it "assigns the requested batch_charity as @batch_charity" do
        batch_charity = BatchCharity.create! valid_attributes
        put :update, {:id => batch_charity.to_param, :batch_charity => valid_attributes}, valid_session
        assigns(:batch_charity).should eq(batch_charity)
      end

      it "redirects to the batch_charity" do
        batch_charity = BatchCharity.create! valid_attributes
        put :update, {:id => batch_charity.to_param, :batch_charity => valid_attributes}, valid_session
        response.should redirect_to(batch_charity)
      end
    end

    describe "with invalid params" do
      it "assigns the batch_charity as @batch_charity" do
        batch_charity = BatchCharity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BatchCharity.any_instance.stub(:save).and_return(false)
        put :update, {:id => batch_charity.to_param, :batch_charity => { "batch_id" => "invalid value" }}, valid_session
        assigns(:batch_charity).should eq(batch_charity)
      end

      it "re-renders the 'edit' template" do
        batch_charity = BatchCharity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BatchCharity.any_instance.stub(:save).and_return(false)
        put :update, {:id => batch_charity.to_param, :batch_charity => { "batch_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested batch_charity" do
      batch_charity = BatchCharity.create! valid_attributes
      expect {
        delete :destroy, {:id => batch_charity.to_param}, valid_session
      }.to change(BatchCharity, :count).by(-1)
    end

    it "redirects to the batch_charities list" do
      batch_charity = BatchCharity.create! valid_attributes
      delete :destroy, {:id => batch_charity.to_param}, valid_session
      response.should redirect_to(batch_charities_url)
    end
  end

end
