require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BuddhasController do

  # This should return the minimal set of attributes required to create a valid
  # Buddha. As you add validations to Buddha, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "product" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BuddhasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all buddhas as @buddhas" do
      buddha = Buddha.create! valid_attributes
      get :index, {}, valid_session
      assigns(:buddhas).should eq([buddha])
    end
  end

  describe "GET show" do
    it "assigns the requested buddha as @buddha" do
      buddha = Buddha.create! valid_attributes
      get :show, {:id => buddha.to_param}, valid_session
      assigns(:buddha).should eq(buddha)
    end
  end

  describe "GET new" do
    it "assigns a new buddha as @buddha" do
      get :new, {}, valid_session
      assigns(:buddha).should be_a_new(Buddha)
    end
  end

  describe "GET edit" do
    it "assigns the requested buddha as @buddha" do
      buddha = Buddha.create! valid_attributes
      get :edit, {:id => buddha.to_param}, valid_session
      assigns(:buddha).should eq(buddha)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Buddha" do
        expect {
          post :create, {:buddha => valid_attributes}, valid_session
        }.to change(Buddha, :count).by(1)
      end

      it "assigns a newly created buddha as @buddha" do
        post :create, {:buddha => valid_attributes}, valid_session
        assigns(:buddha).should be_a(Buddha)
        assigns(:buddha).should be_persisted
      end

      it "redirects to the created buddha" do
        post :create, {:buddha => valid_attributes}, valid_session
        response.should redirect_to(Buddha.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved buddha as @buddha" do
        # Trigger the behavior that occurs when invalid params are submitted
        Buddha.any_instance.stub(:save).and_return(false)
        post :create, {:buddha => { "product" => "invalid value" }}, valid_session
        assigns(:buddha).should be_a_new(Buddha)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Buddha.any_instance.stub(:save).and_return(false)
        post :create, {:buddha => { "product" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested buddha" do
        buddha = Buddha.create! valid_attributes
        # Assuming there are no other buddhas in the database, this
        # specifies that the Buddha created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Buddha.any_instance.should_receive(:update_attributes).with({ "product" => "" })
        put :update, {:id => buddha.to_param, :buddha => { "product" => "" }}, valid_session
      end

      it "assigns the requested buddha as @buddha" do
        buddha = Buddha.create! valid_attributes
        put :update, {:id => buddha.to_param, :buddha => valid_attributes}, valid_session
        assigns(:buddha).should eq(buddha)
      end

      it "redirects to the buddha" do
        buddha = Buddha.create! valid_attributes
        put :update, {:id => buddha.to_param, :buddha => valid_attributes}, valid_session
        response.should redirect_to(buddha)
      end
    end

    describe "with invalid params" do
      it "assigns the buddha as @buddha" do
        buddha = Buddha.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Buddha.any_instance.stub(:save).and_return(false)
        put :update, {:id => buddha.to_param, :buddha => { "product" => "invalid value" }}, valid_session
        assigns(:buddha).should eq(buddha)
      end

      it "re-renders the 'edit' template" do
        buddha = Buddha.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Buddha.any_instance.stub(:save).and_return(false)
        put :update, {:id => buddha.to_param, :buddha => { "product" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested buddha" do
      buddha = Buddha.create! valid_attributes
      expect {
        delete :destroy, {:id => buddha.to_param}, valid_session
      }.to change(Buddha, :count).by(-1)
    end

    it "redirects to the buddhas list" do
      buddha = Buddha.create! valid_attributes
      delete :destroy, {:id => buddha.to_param}, valid_session
      response.should redirect_to(buddhas_url)
    end
  end

end
